[package]
name = "termblast"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
termion = "4.0.2"
thiserror = "1.0.63"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
pedantic = "deny"
nursery = "deny"
